config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "sessions#new"
  get 'player/freeagents', :to => 'players#freeagents_index'

  resources :drafts, only: [:index, :new, :create, :show]
  resources :teams, only: [:index, :new, :create, :show]
  resources :players, only: [:new, :create, :destroy, :show]
  resources :contracts, only: [:new, :create, :destroy, :show, :edit, :update]
  resources :accounts, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :teams
  has_many :players

  validates :account_name, :account_email, :presence => true
  validates :account_email, :uniqueness => true
  validate :password_length

  # Authentication constants
  MIN_LENGTH = 6
  MAX_LENGTH = 50

  def password
    @password ||= BCrypt::Password.new(password_hash)
  end

  def password=(new_password)
    @new_password = new_password
    @password = BCrypt::Password.create(new_password)
    self.password_hash = @password
  end

  def authenticate(given_password)
    self.password == given_password
  end

  def password_length
    if @new_password.length < MIN_LENGTH || @new_password.length > MAX_LENGTH
      errors.add(:password, "must be between #{MIN_LENGTH} and #{MAX_LENGTH} letters long")
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contract.rb
class Contract < ApplicationRecord
  belongs_to :team
  belongs_to :player

  validates :salary, :presence => true, numericality: { only_integer: true }

  after_create :update_player_contract

  def update_player_contract
    player = Player.find(self.player_id)
    player.team_id = self.team_id
    player.save
  end

end

app/models/draft.rb
class Draft < ApplicationRecord

	validates :number_of_rounds, :presence => true, numericality: { only_integer: true }

end

app/models/player.rb
class Player < ApplicationRecord
  has_many :contracts
  has_many :teams, through: :contracts
  #refactor with has_one

  validates :name, :presence => true, :uniqueness => true
  validates :rating, :presence => true, numericality: { only_integer: true }

  def active_contract
    contract = self.contracts.where(active: true).last
    #contract.salary
    if contract != nil
      return contract.salary
    else
      return "n/a"
    end
  end
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :contracts
  has_many :players, through: :contracts

  validates :name, :presence => true, :uniqueness => true
  validates :owner, :presence => true, :uniqueness => true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def new
     @account = Account.new
     render :new
   end

   def create
     @account = Account.new(account_params)
     if @account.save
       session[:account_id] = @account.id
       redirect_to teams_path
     else
       @errors = @account.errors.full_messages
       render :new
     end
   end

   private

   def account_params
     params.require(:account).permit(:password, :account_name, :account_email)
   end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contracts_controller.rb
include DraftHelper

class ContractsController < ApplicationController

  def new
    @freeagent = Player.find(params[:freeagent_id])
    @contract = Contract.new
    @teams = Team.where(account_id: session[:account_id])
  end

  def create
    p "--------------------------"
    p params
   # @contract = Contract.new(team_id: params[:team_id], player_id: params[:player_id], salary: params[:salary], active: true)
   @contract = Contract.new(contract_params)
    if @contract.save
      #take of failed save in both cases
      if session[:draft_id] != nil
        @draft = Draft.find(session[:draft_id])
        next_pick(@draft)
        redirect_to draft_path(@draft.id)
      else
        redirect_to player_path(@contract.player_id)
      end
    else 
      @errors = @contract.errors.full_messages
      @freeagent = Player.find(@contract.player_id)
      @contract = Contract.new
      @teams = Team.where(account_id: session[:account_id])
      render action: "new", freeagent_id: @contract.player_id
    end
  end

  def contract_params
    params.require(:contract).permit(:team_id, :player_id, :salary, :active)
  end

end

app/controllers/drafts_controller.rb
include DraftHelper


class DraftsController < ApplicationController

  def create
    p params
    @draft = Draft.new(draft_params)
    if @draft.save
      create_draft_variables(@draft.id)
      redirect_to draft_path(@draft)
    else
      @errors = @draft.errors.full_messages
      @teams = Team.where(account_id: session[:account_id])
      @draft = Draft.new
      render "teams/index"
    end
  end

  def show
    @draft = Draft.find(params[:id])
    @shuffled_teams = session[:shuffled_teams]
    @teams_objects = Team.where(account_id: session[:account_id])
    # p "------------------------"
    # p session[:shuffled_teams]
    @free_agents = Player.where({:account_id => session[:account_id], :team_id => nil})
    @drafting_team = @shuffled_teams[session[:drafting_counter]]
    @contract = Contract.new




  end

  def draft_params
    params.require(:draft).permit(:number_of_rounds)
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      redirect_to player_path(@player)
    else
      @errors = @player.errors.full_messages
      render new_player_path
    end
  end

  def show
    @player = Player.find(params[:id])
    @active_contract = @player.active_contract
  end

  def freeagents_index
    @freeagents = Player.where({:account_id => session[:account_id], :team_id => nil})
  end

  def player_params
    params.require(:player).permit(:name, :rating, :account_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
      session[:account_id] = nil
    end

     def create
      account = Account.find_by_account_name(params[:account_name])
      if account && account.authenticate(params[:password])
        session[:account_id] = account.id
        redirect_to teams_path
      else
        render "new"
      end
    end

    def destroy
      session[:account_id] = nil
      redirect_to new_session_path
    end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def index
    @teams = Team.where(account_id: session[:account_id])
    @draft = Draft.new
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)
    if @team.save
      redirect_to team_path(@team)
    else
      @errors = @team.errors.full_messages
      render new_team_path
    end
  end

  def show
    @team = Team.find(params[:id])
  end

def team_params
  params.require(:team).permit(:name, :owner, :account_id)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/draft_helper.rb
module DraftHelper
  def create_draft_variables(draft_id)
    session[:draft_id] = draft_id
    session[:round] = 1
    session[:drafting_counter] = 0
    session[:shuffled_teams] = Team.where(account_id: session[:account_id]).shuffle
  end

  def next_pick(draft)
    if session[:drafting_counter] != session[:shuffled_teams].length - 1
      session[:drafting_counter] +=1
    else
      session[:drafting_counter] = 0
      session[:shuffled_teams].reverse!
      session[:round] +=1
      if session[:round] == draft.number_of_rounds + 1
        draft.open = false
        draft.save
      end
    end
  end
end

app/helpers/session_helper.rb
module SessionHelper

  def logged_in?
    if session[:account_id]
      session[:account_id]
    else
      nil
    end
  end

  def logged_in_id
    session[:account_id]
  end

end

app/views/accounts/new.html.erb
<div>
  <section>
    <h1 class="title">Draft Your Presidential Cabinet</h1>
    <div class="banner" >
      <div class="container-fluid">
        <img class="homepic" src="<%= asset_path( 'tumblr_milcogJdzu1s5vsgio2_250.gif') %>"   />
    </div>
  </section>

  <section class="enter-site">
    <img  class="flagpic" src="<%= asset_path( 'american-flag-1459201553ppe.jpg') %>"  />
    <h1 style="padding:15px;">Sign Up...</h1>
    <p style="padding:15px;">How it works: you and your friends get trippy (in whatever way you see fit), then together you create political parties and political candidates that you can then draft to your presidential cabinet!</p>
    <%= render partial:"shared/errors", locals:{errors: @errors} %>
    <%= form_for @account, {action: "create"} do |f| %>
      <fieldset>
        <label for="account_name">Account Name</label><br>
        <%= f.text_field :account_name %><br><br>

        <label for="account_email">Account Email</label><br>
        <%= f.email_field :account_email %><br><br>

        <label for="password">Password</label><br>
        <%= f.password_field :password %><br><br>
        <%= f.submit "Create", class: "btn btn-primary", name: "commit", type: "submit" %>
      </fieldset>
    <% end %>
  </section>
</div>

app/views/contracts/new.html.erb
<div>
  <h2 class="page-title"> Sign Free Agent</h2>

  <section>
    <div style="background-color:#bb0114;color:white;">
      <div class="createpic">
        <img  class="createpic" src="<%= asset_path( 'Richard_Nixon_by_Edmund_S._Valtman_ppmsc.07955.jpg') %>"  />
      </div>
      <div id="create-form">
        <h2 style="padding-bottom: 15px;"><i style="color:#001b7f;"><%= @freeagent.name %></i> </h2>
        <%= form_for @contract, url: contracts_path(@contract), method: :post do |f| %>
          <%= render partial:"shared/errors", locals:{errors: @errors} %>
          <div class="form-field">
            <label for="name">Political Party</label><br>
            <%= f.collection_select :team_id, @teams, :id, :name %>
          </div>
          <div class="form-field">
            <label for="name">Salary</label><br>
            <%= f.number_field :salary,  type: "text", class: "form-control, col-sm-2", id: "salary" %>
          </div>
          <%= f.hidden_field :player_id, :value => @freeagent.id %>
          <%= f.hidden_field :active, :value => :true %>
          <div class="form-field">
            <%= f.submit "Create", class: "btn btn-primary", name: "commit", type: "submit" %>
          </div>
        <% end %>
       </div>
    </div>
  <section>
</div>

app/views/drafts/show.html.erb
<div >


  <section class="draft-details">
    <h2><b style="color:red;">Draft Order</b></h2>
    <ul style="list-style: none;padding: 0px;">
      <% @shuffled_teams.each do |team| %>
      <li>
        <%= team["name"] %>
      </li>
      <% end %>
    </ul>
    <p><b>On The Clock:</b><b style="color:blue;"><%= @drafting_team["name"] %></b></p>
  </section>

  <div class="draftpic">
        <img  class="draftpic" src="<%= asset_path( 'Kanye_West_at_the_2009_Tribeca_Film_Festival.jpg') %>"  />
        <p style="margin-top: 390px;width:50%;text-align: center;margin-left: 25%;color:red;">YOU WOULD BE A FOOL NOT TO DRAFT ME TO YOUR POLITICAL CABINET!</p>
      </div>
  <div style="background-color: #001353;color:white;padding-top: 30px;padding-bottom: 30px;">
    <section class="draft-list" style="display: inline-block;vertical-align: top;width:25%;">
      <div id="team_rosters">
        <h2 style="color: red;">Party Rosters</h2>
        <ol >
          <% @teams_objects.each do |team| %>
          <li><%= team.name %></li>
            <% team.players.each do |player| %>
            <ul>
              <li><%= player.name %></li>
            </ul>
            <% end %>
          <% end %>
        </ol>
      </div>
    </section>

    <%if @draft.open %>
     <section class="draft-list" style="display: inline-block;vertical-align: top;width:20%;margin-left: 45%">
        <h2 style="color: red;text-align: center;">Draft Candidates</h2>
        <% @free_agents.each do |free_agent| %>
          <%= form_for @contract, url: contracts_path(@contract), method: :post do |f| %>
            <%= f.hidden_field :team_id, :value => @drafting_team["id"] %>
            <%= f.hidden_field :salary, :value => 1000 %>
            <%= f.hidden_field :player_id, :value =>free_agent.id %>
            <%= f.hidden_field :active, :value => :true %>
            <div class="form-field" style="text-align: center;">
              <%= f.submit "#{free_agent.name}", class: "btn btn-primary", name: "commit", type: "submit" %>
            </div>
          <% end %>
        <% end %>
      <% else %>
        <h2>Draft is closed!</h2>
        <%= link_to "Go to Teams Page", teams_path %>
      <% end %>
    </section>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FanSports</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar">
      <% if logged_in? %>
        <div class="logged_in-links">
          <%= link_to "[Home]", teams_path %><br>
          <%= link_to "[Logout]", session_path(session[:account_id]), :method => :delete %>
        </div>
        <div class="admin-links">
          <%= link_to "[Create Party]", new_team_path, class: "admin-link" %>
          <%= link_to "[Create Candidate]", new_player_path, class: "admin-link" %>
          <%= link_to "[Sign Free Agent]", player_freeagents_path, class: "admin-link" %>
        </div>
      <% else %>
        <%= link_to "sign up", new_account_path, :method => :get %>
        <%= link_to "sign in", new_session_path, :method => :get %>
      <% end %>
    </nav>
    <%= yield %>
    <footer>
      <p>Thanks 'merica</p>
    </footer>
  </body>
</html>

app/views/players/freeagents_index.html.erb
<div>
  <h2 class="page-title">Free Agents</h2>

  <section style="background-color: #001b7f;padding: 30px;">
    <img style="display: inline-block; vertical-align: top;" class="lil-banner" src="<%= asset_path( 'american-flag-1459201553ppe.jpg') %>"/>
    <div style="display: inline-block; vertical-align: top; padding-left: 20px; padding-right: 20px;" class="list-group, col-sm-4">
      <% @freeagents.each do |freeagent| %>
        <%= link_to "#{freeagent.name}", new_contract_path(freeagent_id: freeagent.id), class: "list-group-item" %>
      <% end %>
    </div>
    <img style="display: inline-block; vertical-align: top;" class="lil-banner" src="<%= asset_path( 'american-flag-1459201553ppe.jpg') %>"/>
  </section>
</div>

app/views/players/new.html.erb
<div>
  <h2 class="page-title"> Create Political Candidate </h2>

  <section>
    <div style="background-color:#bb0114; color:white;">
      <div id="createpicplayer">
        <img  id="createpicplayer" src="<%= asset_path( 'Rally_to_Restore_Sanity_andor_Fear_-_Colbert_2.jpg') %>"  />
      </div>

      <div id="create-form" style="padding-top: 15px;">
        <%= form_for @player, url: players_path(@player), method: :post do |f| %>
            <%= render partial:"shared/errors", locals:{errors: @errors} %>
            <div class="form-field">
              <label for="name">Candidate Name</label><br>
              <%= f.text_field :name, type: "text", class: "form-control, col-sm-4", id: "name" %>
            </div>

            <div class="form-field">
              <label for="rating">Competency</label><br>
              <%= f.text_field :rating, type: "text", class: "form-control, col-sm-4", id: "rating" %>
            </div>

            <%= f.hidden_field :account_id, :value => session[:account_id] %>

            <div class="form-field">
              <%= f.submit "Create", class: "btn btn-primary", name: "commit", type: "submit" %>
            </div>
          <% end %>
      </div>
    </div>
  </section>
</div>

app/views/players/show.html.erb
<div>
  <h2 class="page-title"><%= @player.name %></h2>

  <section>
    <div style="background-color: #8eb2ed;">
      <div style="padding-top: 25px;" id="create-form">
        <div class="createpic">
            <img  class="createpic" src="<%= asset_path( 'american-flag-1459201553ppe.jpg') %>"  />
        </div >
        <h2>Competency: <%= @player.rating %></h2>
        <h3>Active Salary: <%= @active_contract %></h3>
      </div>
    </div>
  </section>
</div>

app/views/shared/_errors.erb
<% if @errors %>
	<div class="error-box">
		<i class="glyphicon glyphicon-exclamation-sign"></i>
		<div>
		<% @errors.each do |error| %>
			<p><%= error %></p>
		<% end %>
		</div>
	</div>
<% end %>